### ISSUE TITLE
issue with nginx

### ISSUE THREAD

**Issue by k1ck3r** [skycube/jqspeedtest#2]
hello,

is there anything additional to configure from nginx point of view, because once the directory is served to nginx, using any of the speedtests included in index.html doesn't start the network test?

thanks in advance

**Comment by k1ck3r** [comment]
i've managed to debug the issue that i had, for nginx there should be the following options under proper location:

        client_max_body_size 100M;
        error_page 405 =200 $uri;

**Comment by k1ck3r** [comment]
ok it seems that the speed test can't run when SSL is enabled in nginx. could you be so kind and let me (us) know how this could be handle within SSL

**Comment by skycube** [comment]
@k1ck3r I believe this has nothing to do with the server type.
I have updated the demo to now allow https connections. Maybe try this:
https://demo.skycube.net/jqspeedtest/

I also updated the the file https://github.com/skycube/jqspeedtest/blob/master/index.html
to ensure its working fine with HTTPS. Let me know how you go.

**Comment by k1ck3r** [comment]
yeah i suppose nginx has nothing to do, but had to mention it.

with your latest additions in index.html testing the download works just fine, but upload and response time doesn't https://node.evilbox.io/speed/ 

also thank you very much for your attention on this, your time is highly appreciated ;)

**Comment by skycube** [comment]
You need to set 2 additional parameters in your nginx config which are not enabled by default:

To overcome the HTTP Error Code 413:
Inside the server section just after `server_name`:
`client_max_body_size 100M;`

To overcome the the post issue:
In the location section:
`error_page 405 =200 $uri;`

I've tested this with a docker image and seems to work perfectly :)

**Comment by k1ck3r** [comment]
Thank you, works flawlessly!!!
